language: python

python: 3.8
cache: pip
env:
    - TOXENV=py36
    - TOXENV=py37
    - TOXENV=py38
    - TOXENV=pep8
    - TOXENV=coverage
before_install:
    - pip install --upgrade pip setuptools
install:
    - pip install tox
script:
    - tox -e $TOXENV
